### ISSUE TITLE
ElastAlert doesn't work on ElasticSearch 5.0

### ISSUE THREAD

**Issue by ThomasdOtreppe** [MainNerve/NetforceDefender#28]
When running ```journalctl -xe -u ElastAlert.service```, we get the following log:
```
Dec 19 19:30:55 ubuntu python2[1276]: WARNING:elasticsearch:GET http://127.0.0.1:9200/logstash-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.008s]
Dec 19 19:30:55 ubuntu python2[1276]: ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')
Dec 19 19:30:55 ubuntu python2[1276]: WARNING:elasticsearch:POST http://127.0.0.1:9200/elastalert_status/elastalert_error?op_type=create [status:400 request:0.007s]
Dec 19 19:30:55 ubuntu python2[1276]: ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: an id must be provided if version type or value are set;')
Dec 19 19:30:55 ubuntu python2[1276]: Traceback (most recent call last):
Dec 19 19:30:55 ubuntu python2[1276]:   File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 1021, in writeback
Dec 19 19:30:55 ubuntu python2[1276]:     doc_type=doc_type, body=body)
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
Dec 19 19:30:55 ubuntu python2[1276]:     return func(*args, params=params, **kwargs)
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 248, in create
Dec 19 19:30:55 ubuntu python2[1276]:     return self.index(index, doc_type, body, id=id, params=params, op_type='create')
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
Dec 19 19:30:55 ubuntu python2[1276]:     return func(*args, params=params, **kwargs)
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 279, in index
Dec 19 19:30:55 ubuntu python2[1276]:     _make_path(index, doc_type, id), params=params, body=body)
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 327, in perform_request
Dec 19 19:30:55 ubuntu python2[1276]:     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 84, in perform_request
Dec 19 19:30:55 ubuntu python2[1276]:     self._raise_error(response.status_code, raw_data)
Dec 19 19:30:55 ubuntu python2[1276]:   File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 113, in _raise_error
Dec 19 19:30:55 ubuntu python2[1276]:     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
Dec 19 19:30:55 ubuntu python2[1276]: RequestError: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: an id must be provided if version type or value are set;')
Dec 19 19:30:55 ubuntu python2[1276]: INFO:elastalert:Ran Alert from logs from 2016-12-19 19:15 PST to 2016-12-19 19:30 PST: 0 query hits, 0 matches, 0 alerts sent
```

Basically, it doesn't work with ES 5.0 yet (this issue has already been reported: Yelp/elastalert#797) and they are working on 5.0 support: Yelp/elastalert#820

**Comment by ThomasdOtreppe** [comment]
Using ElastAlert branch for ES 5.0 for now as workaround until fully stable and it seems to work thanks to the new release of elasticsearch-py and the a recent commit (7e27706bf6d9a9062aaf22fe6a0541104af1bdac)
